import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from "../components/Header"
import Content from "../components/Content"
import Grid from '@mui/material/Grid';


const inter = Inter({ subsets: ['latin'] })
Content
export default function Home() {
  return (
    <>
      <Head>
        <title>My Resume</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid container spacing={0} >
      <Header/>
      <Content />
      </Grid>
    </>
  )
}
